@startuml alumno

class Alumno {
    +String nombre
    +String apellido
    +String email
    +String telefono
    +String direccion
    +String codigoPostal
    +String ciudad
    +Integer edad
    +Boolean esAlumno
    +Boolean esProfesor
    +Boolean esConvenio
    +Integer convenio
    +Date fechaNacimiento
    +Date fechaConvenio
}

Alumno "1" -- "1" Alumno : alumnos

@enduml